package: glibc
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    GLIBC_VERSION=2.17
    GLIBC_HASH=a3b2086d5414e602b4b3d5a8792213feb3be664ffc1efe783a829818d3fca37a
  - >
    GLIBC_VERSION=2.19
    GLIBC_HASH=18ad6db70724699d264add80b1f813630d0141cf3a3558b4e1a7c15f6beac796

before_script:
  - conda update -n root conda-build

script:
  - conda build .

build_targets:
  - conda
