package:
  name: httpd
  version: "{{ environ.get('HTTPD_VERSION') }}"

build:
  number: 6

source:
  fn: "httpd-{{ HTTPD_VERSION }}.tar.gz"
  url: "http://apache.osuosl.org/httpd/httpd-{{ HTTPD_VERSION }}.tar.gz"
  md5: "{{ environ.get('HTTPD_HASH') }}"

requirements:
  build:
    - openssl
    - pcre
    - zlib
  run:
    - openssl
    - pcre
    - zlib

about:
  home: http://httpd.apache.org/
  license: Apache
