package:
  name: celery
  version: "{{ environ.get('CELERY_VERSION') }}"

build:
  number: 0

source:
  fn: "celery-{{ environ.get('CELERY_VERSION') }}.tar.gz"
  url: "https://pypi.python.org/packages/source/c/celery/celery-{{ environ.get('CELERY_VERSION') }}.tar.gz"
  md5: "{{ environ.get('CELERY_HASH') }}"

requirements:
  build:
    - python
    - py-amqp
    - librabbitmq
    - anyjson
    - billiard
    - kombu
    - pytz
  run:
    - python
    - py-amqp
    - librabbitmq
    - anyjson
    - billiard
    - kombu
    - pytz

test:
  commands:
    - python -c 'from celery import Celery'

about:
  home: http://github.com/celery/celery
  license: New BSD
