package:
  name: ruby
  version: "{{ environ.get('RUBY_VERSION') }}"

build:
  number: "{{ environ.get('RUBY_BUILD_NUM') }}"

source:
  fn: "{{ environ.get('RUBY_FN') }}"
  url: "{{ environ.get('RUBY_URL') }}"
  sha256: "{{ environ.get('RUBY_HASH') }}"

test:
  commands:
    - ruby --version
    - ruby -e 'require "rubygems"'
    - gem --version

requirements:
  build:
    - openssl
    - readline
    - yaml
    - zlib
  run:
    - openssl
    - readline
    - yaml
    - zlib

about:
  home: https://www.ruby-lang.org/
  license: BSD
