package:
  name: ruby
  version: 2.1.5

build:
  number: 0

source:
  fn: ruby-2.1.5.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.5.tar.gz
  sha256: 4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100

test:
  commands:
    - ruby --version
    - ruby -e 'require "rubygems"'
    - gem --version

requirements:
  build:
    - openssl
    - readline
    - yaml
    - zlib
  run:
    - openssl
    - readline
    - yaml
    - zlib

about:
  home: https://www.ruby-lang.org/
  license: BSD
