package:
  name: node
  version: 4.1.1

build:
  number: 0

requirements:
  build:
    - python

source:
  fn: node-v4.1.1.tar.gz
  url: https://nodejs.org/dist/v4.1.1/node-v4.1.1.tar.gz
  sha256: 6a610935ff52de713cf2af6a26002322e24fd7933a444436f0817a2b84e15a58 

about:
  home: https://nodejs.org
  license: MIT

