package: git
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - GIT_VERSION=2.3.5

iotimeout: 120

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/asmeurer autoconf
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
