package:
  name: git
  version: "{{ environ.get('GIT_VERSION') }}"

build:
  number: 0

iotimeout: 120

requirements:
  build:
    - openssl
    - zlib
  run:
    - openssl
    - zlib

source:
  git_url: https://github.com/git/git.git
  git_tag: "v{{ environ.get('GIT_VERSION') }}"

about:
  home: http://git-scm.com
  license: LGPLv2.1
