package:
  name: git
  version: "{{ environ.get('GIT_VERSION') }}"

build:
  number: 0

source:
  git_url: https://github.com/git/git.git
  git_tag: "{{ environ.get('GIT_VERSION') }}"

about:
  home: http://git-scm.com
  license: LGPLv2.1
