package: tcl
user: kalefranz

iotimeout: 120

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    TCL_VERSION=8.6.4
    TCL_HASH=9e6ed94c981c1d0c5f5fefb8112d06c6bf4d050a7327e95e71d417c416519c8d

before_script:
  - conda update -n root conda-build

script:
  - conda build .

build_targets:
  - conda
