package:
  name: imagemagick
  version: "{{ environ.get('IMAGEMAGICK_VERSION') }}"

build:
  number: 0

source:
  fn: "{{ IMAGEMAGICK_FN }}"
  url: "http://www.imagemagick.org/download/releases/{{ IMAGEMAGICK_FN }}"
  sha256: "{{ environ.get('IMAGEMAGICK_HASH') }}"

# test:
#   commands:
#     - make check

about:
  home: http://www.imagemagick.org/
  license: Apache
