package: extutils-makemaker
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/asmeurer autoconf
  # - conda install -c https://conda.binstar.org/asmeurer perl
  - conda install -c https://conda.binstar.org/dan_blanchard perl=5.18.2
  - conda install -c https://conda.binstar.org/dan_blanchard perl-cpan

script:
  - conda build --perl 5.18.2 .

build_targets:
  - conda
