package: extutils-makemaker
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

before_script:
  - conda update -n root conda-build
  # - conda install -c dan_blanchard perl=5.18.2
  # - conda install -c dan_blanchard perl-cpan
  - conda config --add channels dan_blanchard

script:
  - conda build --perl 5.18.2 .

build_targets:
  - conda
