package: trollius
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    GUNICORN_VERSION=1.0.4
    GUNICORN_HASH=3631a464d49d0cbfd30ab2918ef2b783

before_script:
  - conda update -n root conda conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
