package: go
user: kalefranz

platform:
  - linux-64

env:
  - GO_VERSION=1.4.2

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
