package: fluentd
user: kalefranz

platform:
  - linux-64

env:
  - FLUENTD_VERSION=0.12.14

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
