package:
  name: "{{ environ.get('BINSTAR_PACKAGE') }}"
  version: "{{ environ.get('FLUENTD_VERSION') }}"

build:
  number: 0

requirements:
  build:
    - ruby >=1.9.3
    - jemalloc
  run:
    - ruby >=1.9.3
    - jemalloc

test:
  commands:
    - |
      export LD_PRELOAD=$PREFIX/lib/libjemalloc.so
      fluentd --setup ./fluent
      fluentd -c ./fluent/fluent.conf -vv &
      sleep 5
      echo '{"json":"message"}' | fluent-cat debug.test
