package:
  name: ruby
  version: 1.9.3

build:
  number: 551

source:
  fn: ruby-1.9.3-p551.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.gz
  sha256: bb5be55cd1f49c95bb05b6f587701376b53d310eb1bb7c76fbd445a1c75b51e8

test:
  commands:
    - ruby --version
    - ruby -e 'require "rubygems"'
    - gem --version

requirements:
  build:
    - openssl
    - readline
    - yaml
    - zlib
  run:
    - openssl
    - readline
    - yaml
    - zlib

about:
  home: https://www.ruby-lang.org/
  license: BSD

