package: ttam-gems
user: kalefranz

platform:
  - linux-64

# engine:
#   - ruby=1.9
#   - ruby=2.1

iotimeout: 480

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
