package:
  name: uwsgi
  version: "{{ environ.get('UWSGI_VERSION') }}"

build:
  number: 0

source:
  fn: "uwsgi-{{ environ.get('UWSGI_VERSION') }}.tar.gz"
  url: "https://pypi.python.org/packages/source/u/uWSGI/uwsgi-{{ environ.get('UWSGI_VERSION') }}.tar.gz"
  md5: "{{ environ.get('UWSGI_HASH') }}"

requirements:
  build:
    - python
    - jansson
    - openssl
    - pcre
    - wheel
    - yaml
    - zlib
  run:
    - python
    - jansson
    - openssl
    - pcre
    - wheel
    - yaml
    - zlib

test:
  commands:
    - uwsgi --help
    - python -c "import uwsgi"
    - python -c "import uwsgidecorators"

about:
  home: http://unbit.com/
  license: GPL2
