package:
  name: consul-ui
  version: 0.5.2

build:
  number: 0

source:
  fn: 0.5.2_web_ui.zip
  url: https://dl.bintray.com/mitchellh/consul/0.5.2_web_ui.zip 
  sha256: ad883aa52e1c0136ab1492bbcedad1210235f26d59719fb6de3ef6464f1ff3b1 

about:
  home: https://consul.io
  license: https://github.com/hashicorp/consul/blob/master/LICENSE

