package:
  name: newrelic-sysmond 
  version: 2.2.0.125

build:
  number: 0

source:
  fn: newrelic-sysmond-2.2.0.125-linux.tar.gz
  url: https://download.newrelic.com/server_monitor/release/newrelic-sysmond-2.2.0.125-linux.tar.gz
  sha256: 92c43cdce10e727e7f17d81c733e421402f62bf7a4b042ce38cb4cb93b5c93f6

test:
  commands:
    - nrsysmond -v

about:
  home: https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/servers-installation-other-linux
  license: Proprietary

