package: cryptopp
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    CRYPTOPP_VERSION=5.5.2
    CRYPTOPP_HASH=a3b2086d5414e602b4b3d5a8792213feb3be664ffc1efe783a829818d3fca37a

before_script:
  - conda update -n root conda-build

script:
  - conda build .

build_targets:
  - conda
