package:
  name: libicu
  version: "{{ environ.get('ICU_VERSION') }}"

build:
  number: 0

source:
  fn: "{{ 'icu_' + environ.get('ICU_VERSION') + '.orig.tar.gz' }}"
  url: "{{ 'https://launchpad.net/ubuntu/+archive/primary/+files/icu_' + environ.get('ICU_VERSION') + '.orig.tar.gz' }}"
  md5: "{{ environ.get('ICU_HASH') }}"

about:
  home: https://www.ruby-lang.org/
  license: BSD
