package:
  name: nginx
  version: 1.9.6

source:
  fn: nginx-1.9.6.tar.gz
  url: http://nginx.org/download/nginx-1.9.6.tar.gz
  sha256: ed501fc6d0eff9d3bc1049cc1ba3a3ac8c602de046acb2a4c108392bbfa865ea
  patches:
    - configure.patch

build:
  number: 2
  no_link: etc/*
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - openssl
    - pcre
    - zlib
  run:
    - openssl
    - pcre
    - zlib

test:
  commands:
    - nginx -V

about:
  home: http://www.nginx.org
  license: 2-clause BSD-like license

