package: pyicu
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  # - >
  #   PYICU_VERSION=1.8
  #   PYICU_HASH=00c8d40e5400f52c8474aa9480e8dbc1
  #   LIBICU_VERSION=4.2.1
  - >
    PYICU_VERSION=0.9
    PYICU_HASH=944e697f5f9554a68f92619c0a3f69e2
    LIBICU_VERSION=4.2.1

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
