package:
  name: uwsgi
  version: 2.0.11.2

build:
  number: 0

source:
  fn: "uwsgi-2.0.11.2.tar.gz"
  url: "https://pypi.python.org/packages/source/u/uWSGI/uwsgi-2.0.11.2.tar.gz"
  md5: 1f02dcbee7f6f61de4b1fd68350cf16f 

requirements:
  build:
    - python
    - jansson
    - openssl
    - pcre
    - wheel
    - yaml
    - zlib
  run:
    - python
    - jansson
    - openssl
    - pcre
    - wheel
    - yaml
    - zlib

test:
  commands:
    - uwsgi --help
    - uwsgi --version

about:
  home: http://unbit.com/
  license: GPL2

