package:
  name: python-cjson
  version: 1.1.0

build:
  number: 0

source:
  fn: python-cjson-1.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/python-cjson/python-cjson-1.1.0.tar.gz
  md5: adb28f42c72ef573dfbd4cdf09676ace

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - "python -c 'import cjson'"

about:
  home: http://ag-projects.com/
  license:  GNU Library or Lesser General Public License (LGPL)
  summary: Fast JSON encoder/decoder for Python
