package: reportlab
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    REPORTLAB_VERSION=2.7
    REPORTLAB_VERSION=78300e6fe8a0d020fc16734a3de80cc4

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
