package: anyjson
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    ANYJSON_VERSION=0.3.3
    ANYJSON_HASH=2ea28d6ec311aeeebaf993cb3008b27c

before_script:
  - conda update -n root conda-build

script:
  - conda build .

build_targets:
  - conda
