package: ant
user: kalefranz

platform:
  - linux-64

env:
  - >
    ANT_VERSION=1.9.4
    ANT_HASH=5beb7949f8c4eff84b20b55c795de0a4
    ANT_JAVA_VERSION=8*
  - >
    ANT_VERSION=1.8.4
    ANT_HASH=4e05e1cc4ea4b56d85bbbc4fe29d1c29
    ANT_JAVA_VERSION=7*

  # - >
  #   ANT_VERSION=1.9.3
  #   ANT_HASH=99ea0e457e9d4f236555621d62399b83
  #   ANT_JAVA_VERSION=7*

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
