package: ant
user: kalefranz

platform:
  - linux-64

env:
  - >
    ANT_VERSION=1.9.4
    ANT_HASH=5beb7949f8c4eff84b20b55c795de0a4

before_script:
  - conda update -n root conda-build
  - conda config --add channels cyclus

script:
  - conda build .

build_targets:
  - conda
