package: ant
user: kalefranz

platform:
  - linux-64

env:
  # - >
  #   ANT_VERSION=1.9.4
  #   ANT_HASH=5beb7949f8c4eff84b20b55c795de0a4
  - >
    ANT_VERSION=1.9.3
    ANT_HASH=99ea0e457e9d4f236555621d62399b83

before_script:
  - conda update -n root conda-build
  - conda config --add channels cyclus

script:
  - conda build .

build_targets:
  - conda
