package:
  name: ant
  version: "{{ environ.get('ANT_VERSION') }}"

build:
  number: 0

source:
  fn: "apache-ant-{{ environ.get('ANT_VERSION') }}-src.tar.gz"
  url: "https://archive.apache.org/dist/ant/source/apache-ant-{{ environ.get('ANT_VERSION') }}-src.tar.gz"
  md5: "{{ environ.get('ANT_HASH') }}"

requirements:
  build:
    - "java-jdk {{ environ.get('ANT_JAVA_VERSION') }}"
  run:
    - "java-jdk {{ environ.get('ANT_JAVA_VERSION') }}"

about:
  home: https://ant.apache.org
  license: Apache
