package:
  name: librabbitmq
  version: "{{ environ.get('LIBRABBITMQ_VERSION') }}"

build:
  number: 0

source:
  fn: "librabbitmq-{{ LIBRABBITMQ_VERSION }}.tar.gz"
  url: "https://pypi.python.org/packages/source/l/librabbitmq/librabbitmq-{{ LIBRABBITMQ_VERSION }}.tar.gz"
  md5: "{{ environ.get('LIBRABBITMQ_HASH') }}"

requirements:
  build:
    - rabbitmq-c
    - python
    - py-amqp
  run:
    - rabbitmq-c
    - python
    - py-amqp

test:
  commands:
    - python -c 'from librabbitmq import Connection'

about:
  home: https://github.com/celery/librabbitmq
  license: GPLv2
