package:
  name: libc-musl
  version: 1.1.11

build:
  number: 0

source:
  fn: musl-1.1.11.tar.gz
  url: http://www.musl-libc.org/releases/musl-1.1.11.tar.gz
  sha256: bb9e6da51b7b12641f5d1abb39705c6c6c1b2fbd20002362948aa736a0aa353f

requirements:
  build:
    - gcc >=4.6

about:
  home: http://www.musl-libc.org/
  license: MIT

