package: cfssl
user: kalefranz

platform:
  - linux-64

env:
  - CFSSL_VERSION=1.0.0

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
