package:
  name: redis
  version: 3.0.5

build:
  number: 0

source:
  fn: redis-3.0.5.tar.gz
  url: http://download.redis.io/releases/redis-3.0.5.tar.gz
  sha256: 4c176826eee909fbdc63db1c15adc22aab42d758043829e556f4331e6a5bd480

requirements:
  build:
    - gcc
    - libc-musl


about:
  home: http://redis.io
  license: BSD

