package:
  name: redis
  version: 2.8.21

build:
  number: 1

source:
  fn: redis-2.8.21.tar.gz
  url: http://download.redis.io/releases/redis-2.8.21.tar.gz
  sha256: 3da371693bb54c22da04d86cab1b871072c8d19bdfbc4f811469b7b53384c563 

about:
  home: http://redis.io
  license: BSD

