package: ruby
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    RUBY_VERSION=2.1.6
    RUBY_BUILD_NUM=0
    RUBY_FN=ruby-2.1.6.tar.gz
    RUBY_URL=http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.6.tar.gz
    RUBY_HASH=1e1362ae7427c91fa53dc9c05aee4ee200e2d7d8970a891c5bd76bee28d28be4
  - >
    RUBY_VERSION=1.9.3
    RUBY_BUILD_NUM=551
    RUBY_FN=ruby-1.9.3-p551.tar.gz
    RUBY_URL=http://cache.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p551.tar.gz
    RUBY_HASH=bb5be55cd1f49c95bb05b6f587701376b53d310eb1bb7c76fbd445a1c75b51e8

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
