package:
  name: tcl
  version: 8.6.4

build:
  number: 1

source:
  fn: "tcl8.6.4-src.tar.gz"
  url: "http://prdownloads.sourceforge.net/tcl/tcl8.6.4-src.tar.gz"
  sha256: 9e6ed94c981c1d0c5f5fefb8112d06c6bf4d050a7327e95e71d417c416519c8d

about:
  home: http://www.tcl.tk/
  license: BSD-style

