package:
  name: ansible
  version: 0.9.0

build:
  number: 0

source:
  fn: python-iptables-0.9.0.tar.gz 
  url: https://pypi.python.org/packages/source/p/python-iptables/python-iptables-0.9.0.tar.gz
  md5: 249d39ce82a5fc23eca3c7e50aa55aeb

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - python -c 'import iptc'

about:
  home: https://github.com/ldx/python-iptables
  license: Apache

