package:
  name: go
  version: "{{ environ.get('GO_VERSION') }}"

build:
  number: 0

requirements:
  build:
    - openssl
    - pcre
    - zlib
  run:
    - openssl
    - pcre
    - zlib

source:
  git_url: https://go.googlesource.com/go
  git_tag: "go{{ environ.get('GO_VERSION') }}"

test:
  commands:
    - go version
    - go gopath
    - go env

about:
  home: https://golang.org
  license: BSD
