package:
  name: mod_python
  version: "{{ environ.get('MOD_PYTHON_VERSION') }}"

build:
  number: 0

source:
  git_url: https://github.com/grisha/mod_python.git
  git_tag: aa9e288e661a3e3d7c3d572b193f00ce28f82a51

requirements:
  build:
    - python
    - httpd
  run:
    - python
    - httpd

about:
  home: http://modpython.org/
  license: Apache
