package: maven
user: kalefranz

platform:
  - linux-64

env:
  - >
    MAVEN_VERSION=3.3.3
    MAVEN_HASH=794b3b7961200c542a7292682d21ba36

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
