package:
  name: readline
  version: 6.2.5

build:
  number: 2

requirements:
  build:
    - ncurses
  run:
    - ncurses

source:
  fn: readline-6.2.5.tar.gz
  url: https://github.com/tpn/readline/archive/6.2.5.tar.gz
  patches:
    - stop-completion-from-appending-space.patch
    - readline-6.2-shlib.patch

about:
  home: http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL 3