package: imagemagick
user: kalefranz

platform:
  - linux-64

env:
  - >
    IMAGEMAGICK_VERSION=6.9.1
    IMAGEMAGICK_FN=ImageMagick-6.9.1-1.tar.gz
    IMAGEMAGICK_HASH=1aa629ab63ee2ba1fd30f12de129d69f4d4c419e4394a2fc263094a49ffb0e8c
  - >
    IMAGEMAGICK_VERSION=6.4.9
    IMAGEMAGICK_FN=ImageMagick-6.4.9-10.tar.gz
    IMAGEMAGICK_HASH=6699677f01e23d68b0e8e6a421bc21f462e04544e8b2310833b9799896b4d226

iotimeout: 240

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
