# source https://github.com/conda/conda-recipes/blob/master/boost/meta.yaml

package:
  name: boost
  version: "{{ environ.get('BOOST_VERSION') }}"

source:
  fn: "boost_{{ environ.get('BOOST_VERSION')|replace('.', '_') }}.tar.bz2"
  url: "http://sourceforge.net/projects/boost/files/boost/{{ environ.get('BOOST_VERSION') }}/boost_{{ environ.get('BOOST_VERSION')|replace('.', '_') }}.tar.bz2"
  sha256: "{{ environ.get('BOOST_HASH') }}"

build:
  number: 5

requirements:
  build:
    - python
    - libicu      [unix]
    - bzip2       [unix]
    - libpython   [win]
  run:
    - libicu      [unix]

about:
  home: http://www.boost.org/
  license: Boost-1.0
