package:
  name: consul
  version: 0.5.2

build:
  number: 0

source:
  fn: 0.5.2_linux_amd64.zip
  url: https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  sha256: 171cf4074bfca3b1e46112105738985783f19c47f4408377241b868affa9d445

test:
  commands:
    - consul version

about:
  home: https://consul.io
  license: https://github.com/hashicorp/consul/blob/master/LICENSE
