package: mysql
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    MYSQL_VERSION=5.6.24
    MYSQL_MAJOR_VERSION=5.6
    MYSQL_HASH=37e27305b67d76883c5902dce59c89d596beee9dca7dbadd4a2e117f8101dfeb

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/asmeurer ncurses

script:
  - conda build .

build_targets:
  - conda
