package: mysql
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  # - >
  #   MYSQL_VERSION=5.6.24
  #   MYSQL_FILENAME=mysql-5.6.24.tar.gz
  #   MYSQL_URL=https://cdn.mysql.com/Downloads/MySQL-5.6/mysql-5.6.24.tar.gz
  #   MYSQL_HASH=37e27305b67d76883c5902dce59c89d596beee9dca7dbadd4a2e117f8101dfeb
  - >
    MYSQL_VERSION=5.5.41
    MYSQL_FILENAME=mysql-5.5_5.5.41.orig.tar.gz
    MYSQL_URL=https://launchpad.net/ubuntu/+archive/primary/+files/mysql-5.5_5.5.41.orig.tar.gz
    MYSQL_HASH=211ace59652eed6fb0e5cfd76834afab

  # - >
  #   MYSQL_VERSION=5.1.73
  #   MYSQL_FILENAME=mysql-5.1.73.tar.gz
  #   MYSQL_URL=http://dev.mysql.com/get/Downloads/MySQL-5.1/mysql-5.1.73.tar.gz
  #   MYSQL_HASH=05ebe21305408b24407d14b77607a3e5ffa3c300e03f1359d3066f301989dcb5

before_script:
  - conda update -n root conda-build
  # - conda install -c asmeurer ncurses
  # - conda install -c asmeurer readline
  # - conda install -c asmeurer libtool
  # - conda install -c asmeurer automake
  # - conda install -c asmeurer autoconf
  - conda config --add channels asmeurer

script:
  - conda build .

build_targets:
  - conda


# sudo conda install -c https://conda.binstar.org/cgat mysql
# sudo conda install -c https://conda.binstar.org/cgat mysql-python
