package:
  name: wheel
  version: "{{ environ.get('WHEEL_VERSION') }}"

build:
  number: 0

source:
  fn: "wheel-{{ environ.get('WHEEL_VERSION') }}.tar.gz"
  url: "https://pypi.python.org/packages/source/w/wheel/wheel-{{ environ.get('WHEEL_VERSION') }}.tar.gz"
  md5: "{{ environ.get('WHEEL_HASH') }}"

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - python -c 'from wheel import paths'

about:
  home: https://bitbucket.org/pypa/wheel
  license: MIT
