package: mod_wsgi
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    MOD_WSGI_VERSION=4.4.11
    MOD_WSGI_HASH=08205d8bd38b3831336b60db9907e82d

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
