package:
  name: mod_wsgi
  version: "{{ environ.get('MOD_WSGI_VERSION') }}"

build:
  number: 0

source:
  fn: "mod_wsgi-{{ MOD_WSGI_VERSION }}.tar.gz"
  url: "https://pypi.python.org/packages/source/m/mod_wsgi/mod_wsgi-{{ MOD_WSGI_VERSION }}.tar.gz"
  md5: "{{ environ.get('MOD_WSGI_HASH') }}"

requirements:
  build:
    - python
    - httpd
  run:
    - python
    - httpd

about:
  home: https://pypi.python.org/pypi/mod_wsgi
  license: Apache
