package: ncurses
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/rustychris patch

script:
  - conda build .

build_targets:
  - conda
