package: ruby-ffi
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
