package:
  name: jcc
  version: "{{ environ.get('JCC_VERSION') }}"

build:
  number: 0

source:
  fn: "JCC-{{ environ.get('JCC_VERSION') }}.tar.gz"
  url: "https://pypi.python.org/packages/source/J/JCC/JCC-{{ environ.get('JCC_VERSION') }}.tar.gz"
  md5: "{{ environ.get('JCC_HASH') }}"

requirements:
  build:
    - java-jdk
    - python
    - setuptools
  run:
    - java-jdk
    - python

test:
  commands:
    - export JAVA_HOME=$(readlink -f $PREFIX/bin/java | sed "s:/bin/java::")
    - export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH
    - printenv
    - python -c 'import jcc'

about:
  home: http://lucene.apache.org/pylucene/jcc/index.html
  license: Apache
