package: pylucene
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    PYLUCENE_VERSION=3.6.2
    PYLUCENE_FN=pylucene-3.6.2-1-src.tar.gz
    PYLUCENE_HASH=d3cf4c3850b2da784def272999e94463be381b620d131d3b933ca0af65fadf9b
    PYLUCENE_JAVA_VERSION=7*
  - >
    PYLUCENE_VERSION=4.9.0
    PYLUCENE_FN=pylucene-4.9.0-0-src.tar.gz
    PYLUCENE_HASH=8578ebc8e9da06321d42b5622b6f5ac5db340123f99955d86190171c13f01a07
    PYLUCENE_JAVA_VERSION=8*

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/rustychris patch
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
