package:
  name: pylucene
  version: "{{ environ.get('PYLUCENE_VERSION') }}"

build:
  number: 0

source:
  fn: "{{ environ.get('PYLUCENE_FN') }}"
  url: "https://s3-us-west-2.amazonaws.com/repo.public.23andme.io/{{ environ.get('PYLUCENE_FN') }}"
  sha256: "{{ environ.get('PYLUCENE_HASH') }}"
  patches:
    - makefile.patch

requirements:
  build:
    - python
    - "java-jdk {{ environ.get('PYLUCENE_JAVA_VERSION') }}"
    - jcc
    - ant
  run:
    - python
    - "java-jdk {{ environ.get('PYLUCENE_JAVA_VERSION') }}"  # TODO: switch to java-jre
    - jcc

test:
  commands:
    - export LD_LIBRARY_PATH=$PREFIX/lib:$PREFIX/jre/lib:$PREFIX/jre/lib/amd64:$PREFIX/jre/lib/amd64/server:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH=$SP_DIR:$LD_LIBRARY_PATH
    - ls -al /opt/miniconda/envs/_build/lib/python2.7/site-packages
    - python -c 'import lucene; lucene.initVM()'

about:
  home: https://lucene.apache.org/pylucene/
  license: Apache
