package: mysql-python
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  # - >
  #   MYSQL_PYTHON_VERSION=1.2.5
  #   MYSQL_PYTHON_HASH=654f75b302db6ed8dc5a898c625e030c
  #   MYSQL_VERSION=5.5*
  - >
    MYSQL_PYTHON_VERSION=1.2.4
    MYSQL_PYTHON_HASH=ddf2386daf10a97af115ffad2ed4a9a0
    MYSQL_VERSION=5.5*

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/rustychris patch
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
