package:
  name: mysql-python
  version: "{{ environ.get('MYSQL_PYTHON_VERSION') }}"

build:
  number: 1

source:
  fn: "mysql-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  url: "https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  md5: "{{ environ.get('MYSQL_PYTHON_HASH') }}"
  patches:
    - "MySQL-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}-timeout.patch"

requirements:
  build:
    - ncurses
    - python
    - ncurses
    - mysql-client >=5.1*
    - mysql-server 5.1*  # because mysql_config not in mysql-client
  run:
    - ncurses
    - python
    - mysql-client >=5.1*
  patches:
    - ttam-django0.96.patch
    - ttam-django0.96.patch1
    - ttam-django0.96-tzinfo.patch
    - ttam-django0.96-md5-to-hashlib.patch
    - ttam-django0.96-wsgi-is-secure.patch
    - ttam-django0.96-wsgi-handler-lock.patch

test:
  commands:
    - python -c 'import MySQLdb'

about:
  home: https://github.com/farcepest/MySQLdb1
  license: GPL
