package:
  name: mysql-python
  version: "{{ environ.get('MYSQL_PYTHON_VERSION') }}"

build:
  number: 0

source:
  fn: "mysql-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  url: "https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  md5: "{{ environ.get('MYSQL_PYTHON_HASH') }}"

requirements:
  build:
    - ncurses
    - python
    - ncurses
    - mysql-client
    - mysql-server  # because mysql_config not in mysql-client
  run:
    - ncurses
    - python
    - mysql-client

test:
  commands:
    - python -c 'import MySQLdb'

about:
  home: https://github.com/farcepest/MySQLdb1
  license: GPL
