package:
  name: mysql-python
  version: "{{ environ.get('MYSQL_PYTHON_VERSION') }}"

build:
  number: 1

source:
  fn: "mysql-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  url: "https://pypi.python.org/packages/source/M/MySQL-python/MySQL-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}.zip"
  md5: "{{ environ.get('MYSQL_PYTHON_HASH') }}"
  patches:
    - "MySQL-python-{{ environ.get('MYSQL_PYTHON_VERSION') }}-timeout.patch"

requirements:
  build:
    - ncurses
    - python
    - ncurses
    - "mysql-client {{ environ.get('MYSQL_VERSION') }}"
    - "mysql-server {{ environ.get('MYSQL_VERSION') }}"  # because mysql_config not in mysql-client
  run:
    - ncurses
    - python
    - "mysql-client {{ environ.get('MYSQL_VERSION') }}"

test:
  commands:
    - 'export LD_LIBRARY_PATH=$LIBRARY_PATH:$LIBRARY_PATH/mysql && python -c "import MySQLdb"'

about:
  home: https://github.com/farcepest/MySQLdb1
  license: GPL
