package: kombu
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    KOMBU_VERSION=3.0.24
    KOMBU_HASH=37c8b5084ac83b8a6f5ff9f157cac0e9

before_script:
  - conda update -n root conda-build
  - conda config --add channels kalefranz

script:
  - conda build .

build_targets:
  - conda
