package: redis
user: kalefranz

platform:
  - linux-64

engine:
  - python=2

env:
  - >
    REDIS_VERSION=2.8.19
    REDIS_HASH=29bb08abfc3d392b2f0c3e7f48ec46dd09ab1023f9a5575fc2a93546f4ca5145
  - >
    REDIS_VERSION=3.0.0
    REDIS_HASH=654c95c6236692dcb916fccba9a34d0877cc91338c8b6a372511e6eb080e34bf

before_script:
  - conda update -n root conda-build
  - conda install -c https://conda.binstar.org/kalefranz tcl

script:
  - conda build .

build_targets:
  - conda
