package:
  name: redis
  version: "{{ environ.get('REDIS_VERSION') }}"

build:
  number: 0

source:
  fn: "redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  url: "http://download.redis.io/releases/redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  sha256: "{{ environ.get('REDIS_HASH') }}"

test:
  commands:
    - conda install -c kalefranz tcl
    - cd $SRC_DIR
    - tclsh8.6 tests/test_helper.tcl

about:
  home: http://redis.io
  license: BSD


