package:
  name: redis
  version: "{{ environ.get('REDIS_VERSION') }}"

build:
  number: 0

source:
  fn: "redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  url: "http://download.redis.io/releases/redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  sha256: "{{ environ.get('REDIS_HASH') }}"

# requirements:
#   build:
#     - tcl

test:
  commands:
    - conda install -c kalefranz tcl
    - printenv
    - conda install -c https://conda.binstar.org/dan_blanchard perl-file-which
    - which -a which
    - which -a tclsh8.6
    - ls -al /home/binstar/env/bin/tclsh8.6
    - $SRC_DIR/runtest

about:
  home: http://redis.io
  license: BSD


