package:
  name: redis
  version: "{{ environ.get('REDIS_VERSION') }}"

build:
  number: 0

source:
  fn: "redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  url: "http://download.redis.io/releases/redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  sha256: "{{ environ.get('REDIS_HASH') }}"

# requirements:
#   build:
#     - tcl

test:
  commands:
    - conda install -c kalefranz tcl
    - $CONDA_DEFAULT_ENV/bin/tclsh8.6 $SRC_DIR/tests/test_helper.tcl

about:
  home: http://redis.io
  license: BSD


