package:
  name: redis
  version: "{{ environ.get('REDIS_VERSION') }}"

build:
  number: 0

source:
  fn: "redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  url: "http://download.redis.io/releases/redis-{{ environ.get('REDIS_VERSION') }}.tar.gz"
  sha256: "{{ environ.get('REDIS_HASH') }}"

test:
  commands:
    - make test

about:
  home: http://redis.io
  license: BSD


